import { Track } from "@spotify/web-api-ts-sdk";
import { json } from "stream/consumers";

const testTracksJson = `[
    {
        "album": {
            "album_type": "COMPILATION",
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/3dXaa6jwM7B52GZpaJEIr5"
                    },
                    "href": "https://api.spotify.com/v1/artists/3dXaa6jwM7B52GZpaJEIr5",
                    "id": "3dXaa6jwM7B52GZpaJEIr5",
                    "name": "Puddle Of Mudd",
                    "type": "artist",
                    "uri": "spotify:artist:3dXaa6jwM7B52GZpaJEIr5"
                }
            ],
            "available_markets": [],
            "external_urls": {
                "spotify": "https://open.spotify.com/album/1RyTWaYknYhKggKUMNHboG"
            },
            "href": "https://api.spotify.com/v1/albums/1RyTWaYknYhKggKUMNHboG",
            "id": "1RyTWaYknYhKggKUMNHboG",
            "images": [
                {
                    "height": 640,
                    "url": "https://i.scdn.co/image/ab67616d0000b273bd7f64a483632fc84bc99522",
                    "width": 640
                },
                {
                    "height": 300,
                    "url": "https://i.scdn.co/image/ab67616d00001e02bd7f64a483632fc84bc99522",
                    "width": 300
                },
                {
                    "height": 64,
                    "url": "https://i.scdn.co/image/ab67616d00004851bd7f64a483632fc84bc99522",
                    "width": 64
                }
            ],
            "name": "Best Of",
            "release_date": "2010-01-01",
            "release_date_precision": "day",
            "total_tracks": 12,
            "type": "album",
            "uri": "spotify:album:1RyTWaYknYhKggKUMNHboG"
        },
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/3dXaa6jwM7B52GZpaJEIr5"
                },
                "href": "https://api.spotify.com/v1/artists/3dXaa6jwM7B52GZpaJEIr5",
                "id": "3dXaa6jwM7B52GZpaJEIr5",
                "name": "Puddle Of Mudd",
                "type": "artist",
                "uri": "spotify:artist:3dXaa6jwM7B52GZpaJEIr5"
            }
        ],
        "available_markets": [],
        "disc_number": 1,
        "duration_ms": 210280,
        "explicit": false,
        "external_ids": {
            "isrc": "USUM70741373"
        },
        "external_urls": {
            "spotify": "https://open.spotify.com/track/7zIHMdEBTHlk6OFSNvfLAa"
        },
        "href": "https://api.spotify.com/v1/tracks/7zIHMdEBTHlk6OFSNvfLAa",
        "id": "7zIHMdEBTHlk6OFSNvfLAa",
        "is_local": false,
        "name": "Psycho",
        "popularity": 0,
        "preview_url": null,
        "track_number": 9,
        "type": "track",
        "uri": "spotify:track:7zIHMdEBTHlk6OFSNvfLAa"
    },
    {
        "album": {
            "album_type": "ALBUM",
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/0RqtSIYZmd4fiBKVFqyIqD"
                    },
                    "href": "https://api.spotify.com/v1/artists/0RqtSIYZmd4fiBKVFqyIqD",
                    "id": "0RqtSIYZmd4fiBKVFqyIqD",
                    "name": "Thirty Seconds To Mars",
                    "type": "artist",
                    "uri": "spotify:artist:0RqtSIYZmd4fiBKVFqyIqD"
                }
            ],
            "available_markets": [
                "AE",
                "BH",
                "BN",
                "BT",
                "CA",
                "HK",
                "ID",
                "IL",
                "IN",
                "IQ",
                "JO",
                "JP",
                "KH",
                "KR",
                "KW",
                "LA",
                "LB",
                "LK",
                "MN",
                "MO",
                "MV",
                "MY",
                "NP",
                "OM",
                "PH",
                "PK",
                "PW",
                "QA",
                "SA",
                "SG",
                "TH",
                "TL",
                "TW",
                "US",
                "VN"
            ],
            "external_urls": {
                "spotify": "https://open.spotify.com/album/1C2qK6SqFughWOoP0qSciv"
            },
            "href": "https://api.spotify.com/v1/albums/1C2qK6SqFughWOoP0qSciv",
            "id": "1C2qK6SqFughWOoP0qSciv",
            "images": [
                {
                    "height": 640,
                    "url": "https://i.scdn.co/image/ab67616d0000b273815ae107627f1ad2502b35dc",
                    "width": 640
                },
                {
                    "height": 300,
                    "url": "https://i.scdn.co/image/ab67616d00001e02815ae107627f1ad2502b35dc",
                    "width": 300
                },
                {
                    "height": 64,
                    "url": "https://i.scdn.co/image/ab67616d00004851815ae107627f1ad2502b35dc",
                    "width": 64
                }
            ],
            "name": "LOVE LUST FAITH + DREAMS",
            "release_date": "2013-01-01",
            "release_date_precision": "day",
            "total_tracks": 12,
            "type": "album",
            "uri": "spotify:album:1C2qK6SqFughWOoP0qSciv"
        },
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/0RqtSIYZmd4fiBKVFqyIqD"
                },
                "href": "https://api.spotify.com/v1/artists/0RqtSIYZmd4fiBKVFqyIqD",
                "id": "0RqtSIYZmd4fiBKVFqyIqD",
                "name": "Thirty Seconds To Mars",
                "type": "artist",
                "uri": "spotify:artist:0RqtSIYZmd4fiBKVFqyIqD"
            }
        ],
        "available_markets": [
            "AE",
            "BH",
            "BN",
            "BT",
            "CA",
            "HK",
            "ID",
            "IL",
            "IN",
            "IQ",
            "JO",
            "JP",
            "KH",
            "KR",
            "KW",
            "LA",
            "LB",
            "LK",
            "MN",
            "MO",
            "MV",
            "MY",
            "NP",
            "OM",
            "PH",
            "PK",
            "PW",
            "QA",
            "SA",
            "SG",
            "TH",
            "TL",
            "TW",
            "US",
            "VN"
        ],
        "disc_number": 1,
        "duration_ms": 247813,
        "explicit": false,
        "external_ids": {
            "isrc": "USVI21300024"
        },
        "external_urls": {
            "spotify": "https://open.spotify.com/track/1mMe0felnLtY2QjR7VcgrA"
        },
        "href": "https://api.spotify.com/v1/tracks/1mMe0felnLtY2QjR7VcgrA",
        "id": "1mMe0felnLtY2QjR7VcgrA",
        "is_local": false,
        "name": "Do Or Die",
        "popularity": 25,
        "preview_url": null,
        "track_number": 9,
        "type": "track",
        "uri": "spotify:track:1mMe0felnLtY2QjR7VcgrA"
    },
    {
        "album": {
            "album_type": "ALBUM",
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/1YPYaJyUobMi0eABhZo92N"
                    },
                    "href": "https://api.spotify.com/v1/artists/1YPYaJyUobMi0eABhZo92N",
                    "id": "1YPYaJyUobMi0eABhZo92N",
                    "name": "Half Japanese",
                    "type": "artist",
                    "uri": "spotify:artist:1YPYaJyUobMi0eABhZo92N"
                }
            ],
            "available_markets": [],
            "external_urls": {
                "spotify": "https://open.spotify.com/album/4M9gPAlAZrnDvuzw6iJseQ"
            },
            "href": "https://api.spotify.com/v1/albums/4M9gPAlAZrnDvuzw6iJseQ",
            "id": "4M9gPAlAZrnDvuzw6iJseQ",
            "images": [
                {
                    "height": 640,
                    "url": "https://i.scdn.co/image/ab67616d0000b273677c6e15a312d1bb2b187fee",
                    "width": 640
                },
                {
                    "height": 300,
                    "url": "https://i.scdn.co/image/ab67616d00001e02677c6e15a312d1bb2b187fee",
                    "width": 300
                },
                {
                    "height": 64,
                    "url": "https://i.scdn.co/image/ab67616d00004851677c6e15a312d1bb2b187fee",
                    "width": 64
                }
            ],
            "name": "Overjoyed",
            "release_date": "2014-09-02",
            "release_date_precision": "day",
            "total_tracks": 12,
            "type": "album",
            "uri": "spotify:album:4M9gPAlAZrnDvuzw6iJseQ"
        },
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/1YPYaJyUobMi0eABhZo92N"
                },
                "href": "https://api.spotify.com/v1/artists/1YPYaJyUobMi0eABhZo92N",
                "id": "1YPYaJyUobMi0eABhZo92N",
                "name": "Half Japanese",
                "type": "artist",
                "uri": "spotify:artist:1YPYaJyUobMi0eABhZo92N"
            }
        ],
        "available_markets": [],
        "disc_number": 1,
        "duration_ms": 257074,
        "explicit": false,
        "external_ids": {
            "isrc": "USJZA1415104"
        },
        "external_urls": {
            "spotify": "https://open.spotify.com/track/351zlSrEZvnCB9Nbxi0dz0"
        },
        "href": "https://api.spotify.com/v1/tracks/351zlSrEZvnCB9Nbxi0dz0",
        "id": "351zlSrEZvnCB9Nbxi0dz0",
        "is_local": false,
        "name": "Do It Nation",
        "popularity": 0,
        "preview_url": null,
        "track_number": 4,
        "type": "track",
        "uri": "spotify:track:351zlSrEZvnCB9Nbxi0dz0"
    },
    {
        "album": {
            "album_type": "ALBUM",
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/77oD8X9qLXZhpbCjv53l5n"
                    },
                    "href": "https://api.spotify.com/v1/artists/77oD8X9qLXZhpbCjv53l5n",
                    "id": "77oD8X9qLXZhpbCjv53l5n",
                    "name": "Mercury Rev",
                    "type": "artist",
                    "uri": "spotify:artist:77oD8X9qLXZhpbCjv53l5n"
                }
            ],
            "available_markets": [],
            "external_urls": {
                "spotify": "https://open.spotify.com/album/6uLSZ42KZz2LMIubkatdM9"
            },
            "href": "https://api.spotify.com/v1/albums/6uLSZ42KZz2LMIubkatdM9",
            "id": "6uLSZ42KZz2LMIubkatdM9",
            "images": [
                {
                    "height": 640,
                    "url": "https://i.scdn.co/image/ab67616d0000b273ebc28c55416472a89dda2b80",
                    "width": 640
                },
                {
                    "height": 300,
                    "url": "https://i.scdn.co/image/ab67616d00001e02ebc28c55416472a89dda2b80",
                    "width": 300
                },
                {
                    "height": 64,
                    "url": "https://i.scdn.co/image/ab67616d00004851ebc28c55416472a89dda2b80",
                    "width": 64
                }
            ],
            "name": "Deserter's Songs",
            "release_date": "1998",
            "release_date_precision": "year",
            "total_tracks": 11,
            "type": "album",
            "uri": "spotify:album:6uLSZ42KZz2LMIubkatdM9"
        },
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/77oD8X9qLXZhpbCjv53l5n"
                },
                "href": "https://api.spotify.com/v1/artists/77oD8X9qLXZhpbCjv53l5n",
                "id": "77oD8X9qLXZhpbCjv53l5n",
                "name": "Mercury Rev",
                "type": "artist",
                "uri": "spotify:artist:77oD8X9qLXZhpbCjv53l5n"
            }
        ],
        "available_markets": [],
        "disc_number": 1,
        "duration_ms": 225333,
        "explicit": false,
        "external_ids": {
            "isrc": "GBUM71102311"
        },
        "external_urls": {
            "spotify": "https://open.spotify.com/track/5ecF3MhOOM4bAZQad4HTy1"
        },
        "href": "https://api.spotify.com/v1/tracks/5ecF3MhOOM4bAZQad4HTy1",
        "id": "5ecF3MhOOM4bAZQad4HTy1",
        "is_local": false,
        "name": "Goddess on a Hiway - Remastered",
        "popularity": 0,
        "preview_url": null,
        "track_number": 8,
        "type": "track",
        "uri": "spotify:track:5ecF3MhOOM4bAZQad4HTy1"
    },
    {
        "album": {
            "album_type": "COMPILATION",
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/3yY2gUcIsjMr8hjo51PoJ8"
                    },
                    "href": "https://api.spotify.com/v1/artists/3yY2gUcIsjMr8hjo51PoJ8",
                    "id": "3yY2gUcIsjMr8hjo51PoJ8",
                    "name": "The Smiths",
                    "type": "artist",
                    "uri": "spotify:artist:3yY2gUcIsjMr8hjo51PoJ8"
                }
            ],
            "available_markets": [
                "AR",
                "AU",
                "AT",
                "BE",
                "BO",
                "BR",
                "BG",
                "CA",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DK",
                "DO",
                "DE",
                "EC",
                "EE",
                "SV",
                "FI",
                "FR",
                "GR",
                "GT",
                "HN",
                "HK",
                "HU",
                "IS",
                "IE",
                "IT",
                "LV",
                "LT",
                "LU",
                "MY",
                "MT",
                "MX",
                "NL",
                "NZ",
                "NI",
                "NO",
                "PA",
                "PY",
                "PE",
                "PH",
                "PL",
                "PT",
                "SG",
                "SK",
                "ES",
                "SE",
                "CH",
                "TW",
                "TR",
                "UY",
                "US",
                "GB",
                "AD",
                "MC",
                "ID",
                "JP",
                "TH",
                "VN",
                "RO",
                "IL",
                "ZA",
                "SA",
                "AE",
                "BH",
                "QA",
                "OM",
                "KW",
                "EG",
                "MA",
                "DZ",
                "TN",
                "LB",
                "JO",
                "IN",
                "BY",
                "KZ",
                "MD",
                "UA",
                "AL",
                "BA",
                "HR",
                "ME",
                "MK",
                "RS",
                "SI",
                "KR",
                "BD",
                "PK",
                "LK",
                "GH",
                "KE",
                "NG",
                "TZ",
                "UG",
                "AG",
                "AM",
                "BS",
                "BB",
                "BZ",
                "BW",
                "BF",
                "CV",
                "CW",
                "DM",
                "FJ",
                "GM",
                "GD",
                "GW",
                "HT",
                "JM",
                "LS",
                "LR",
                "MW",
                "ML",
                "FM",
                "NA",
                "NE",
                "PG",
                "SM",
                "ST",
                "SN",
                "SC",
                "SL",
                "KN",
                "LC",
                "VC",
                "TL",
                "TT",
                "AZ",
                "BN",
                "BI",
                "KH",
                "CM",
                "TD",
                "KM",
                "GQ",
                "SZ",
                "GA",
                "GN",
                "KG",
                "LA",
                "MO",
                "MR",
                "MN",
                "NP",
                "RW",
                "TG",
                "UZ",
                "ZW",
                "BJ",
                "MG",
                "MU",
                "MZ",
                "AO",
                "CI",
                "DJ",
                "ZM",
                "CD",
                "CG",
                "IQ",
                "LY",
                "TJ",
                "VE",
                "ET",
                "XK"
            ],
            "external_urls": {
                "spotify": "https://open.spotify.com/album/30g571JKoxs8AnsgAViV2J"
            },
            "href": "https://api.spotify.com/v1/albums/30g571JKoxs8AnsgAViV2J",
            "id": "30g571JKoxs8AnsgAViV2J",
            "images": [
                {
                    "height": 640,
                    "url": "https://i.scdn.co/image/ab67616d0000b273100a0d5e27dd8bee57cdaf9f",
                    "width": 640
                },
                {
                    "height": 300,
                    "url": "https://i.scdn.co/image/ab67616d00001e02100a0d5e27dd8bee57cdaf9f",
                    "width": 300
                },
                {
                    "height": 64,
                    "url": "https://i.scdn.co/image/ab67616d00004851100a0d5e27dd8bee57cdaf9f",
                    "width": 64
                }
            ],
            "name": "Complete",
            "release_date": "2011-09-26",
            "release_date_precision": "day",
            "total_tracks": 106,
            "type": "album",
            "uri": "spotify:album:30g571JKoxs8AnsgAViV2J"
        },
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/3yY2gUcIsjMr8hjo51PoJ8"
                },
                "href": "https://api.spotify.com/v1/artists/3yY2gUcIsjMr8hjo51PoJ8",
                "id": "3yY2gUcIsjMr8hjo51PoJ8",
                "name": "The Smiths",
                "type": "artist",
                "uri": "spotify:artist:3yY2gUcIsjMr8hjo51PoJ8"
            }
        ],
        "available_markets": [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GD",
            "GW",
            "HT",
            "JM",
            "LS",
            "LR",
            "MW",
            "ML",
            "FM",
            "NA",
            "NE",
            "PG",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "KN",
            "LC",
            "VC",
            "TL",
            "TT",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK"
        ],
        "disc_number": 1,
        "duration_ms": 193133,
        "explicit": false,
        "external_ids": {
            "isrc": "GBCRL0800316"
        },
        "external_urls": {
            "spotify": "https://open.spotify.com/track/084eENRLEaLFYb74I5uUCZ"
        },
        "href": "https://api.spotify.com/v1/tracks/084eENRLEaLFYb74I5uUCZ",
        "id": "084eENRLEaLFYb74I5uUCZ",
        "is_local": false,
        "name": "Last Night I Dreamt That Somebody Loved Me - 2008 Remaster",
        "popularity": 28,
        "preview_url": "https://p.scdn.co/mp3-preview/00ec5d487fd4b771a79339bbf0df786c0daf04b4?cid=9d8e34b48e744e6e868879cd20d1a9a3",
        "track_number": 104,
        "type": "track",
        "uri": "spotify:track:084eENRLEaLFYb74I5uUCZ"
    },
    {
        "album": {
            "album_type": "SINGLE",
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/3NmdKZUM96z7NGvL35g5PC"
                    },
                    "href": "https://api.spotify.com/v1/artists/3NmdKZUM96z7NGvL35g5PC",
                    "id": "3NmdKZUM96z7NGvL35g5PC",
                    "name": "The Rentals",
                    "type": "artist",
                    "uri": "spotify:artist:3NmdKZUM96z7NGvL35g5PC"
                }
            ],
            "available_markets": [],
            "external_urls": {
                "spotify": "https://open.spotify.com/album/29kmyhS95enP5KgvmfGcYk"
            },
            "href": "https://api.spotify.com/v1/albums/29kmyhS95enP5KgvmfGcYk",
            "id": "29kmyhS95enP5KgvmfGcYk",
            "images": [
                {
                    "height": 640,
                    "url": "https://i.scdn.co/image/ab67616d0000b273c742f8dc1031bd54c860301e",
                    "width": 640
                },
                {
                    "height": 300,
                    "url": "https://i.scdn.co/image/ab67616d00001e02c742f8dc1031bd54c860301e",
                    "width": 300
                },
                {
                    "height": 64,
                    "url": "https://i.scdn.co/image/ab67616d00004851c742f8dc1031bd54c860301e",
                    "width": 64
                }
            ],
            "name": "Thought Of Sound",
            "release_date": "2014-06-04",
            "release_date_precision": "day",
            "total_tracks": 1,
            "type": "album",
            "uri": "spotify:album:29kmyhS95enP5KgvmfGcYk"
        },
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/3NmdKZUM96z7NGvL35g5PC"
                },
                "href": "https://api.spotify.com/v1/artists/3NmdKZUM96z7NGvL35g5PC",
                "id": "3NmdKZUM96z7NGvL35g5PC",
                "name": "The Rentals",
                "type": "artist",
                "uri": "spotify:artist:3NmdKZUM96z7NGvL35g5PC"
            }
        ],
        "available_markets": [],
        "disc_number": 1,
        "duration_ms": 224165,
        "explicit": false,
        "external_ids": {
            "isrc": "US3R41427807"
        },
        "external_urls": {
            "spotify": "https://open.spotify.com/track/1dmaXl48kB8627pNVww5fb"
        },
        "href": "https://api.spotify.com/v1/tracks/1dmaXl48kB8627pNVww5fb",
        "id": "1dmaXl48kB8627pNVww5fb",
        "is_local": false,
        "name": "Thought Of Sound",
        "popularity": 0,
        "preview_url": null,
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:1dmaXl48kB8627pNVww5fb"
    },
    {
        "album": {
            "album_type": "ALBUM",
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/3wury2nd8idV4GecUg5xze"
                    },
                    "href": "https://api.spotify.com/v1/artists/3wury2nd8idV4GecUg5xze",
                    "id": "3wury2nd8idV4GecUg5xze",
                    "name": "Primal Scream",
                    "type": "artist",
                    "uri": "spotify:artist:3wury2nd8idV4GecUg5xze"
                }
            ],
            "available_markets": [],
            "external_urls": {
                "spotify": "https://open.spotify.com/album/6kcrRSLUUfRV6we1fHFvDV"
            },
            "href": "https://api.spotify.com/v1/albums/6kcrRSLUUfRV6we1fHFvDV",
            "id": "6kcrRSLUUfRV6we1fHFvDV",
            "images": [
                {
                    "height": 640,
                    "url": "https://i.scdn.co/image/ab67616d0000b273727391987f496ca878f7951e",
                    "width": 640
                },
                {
                    "height": 300,
                    "url": "https://i.scdn.co/image/ab67616d00001e02727391987f496ca878f7951e",
                    "width": 300
                },
                {
                    "height": 64,
                    "url": "https://i.scdn.co/image/ab67616d00004851727391987f496ca878f7951e",
                    "width": 64
                }
            ],
            "name": "More Light",
            "release_date": "2013-06-18",
            "release_date_precision": "day",
            "total_tracks": 13,
            "type": "album",
            "uri": "spotify:album:6kcrRSLUUfRV6we1fHFvDV"
        },
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/3wury2nd8idV4GecUg5xze"
                },
                "href": "https://api.spotify.com/v1/artists/3wury2nd8idV4GecUg5xze",
                "id": "3wury2nd8idV4GecUg5xze",
                "name": "Primal Scream",
                "type": "artist",
                "uri": "spotify:artist:3wury2nd8idV4GecUg5xze"
            }
        ],
        "available_markets": [],
        "disc_number": 1,
        "duration_ms": 540733,
        "explicit": false,
        "external_ids": {
            "isrc": "GBBGB1300011"
        },
        "external_urls": {
            "spotify": "https://open.spotify.com/track/65ZWQ9O1QBBUj9G8uM03Kn"
        },
        "href": "https://api.spotify.com/v1/tracks/65ZWQ9O1QBBUj9G8uM03Kn",
        "id": "65ZWQ9O1QBBUj9G8uM03Kn",
        "is_local": false,
        "name": "2013",
        "popularity": 0,
        "preview_url": null,
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:65ZWQ9O1QBBUj9G8uM03Kn"
    },
    {
        "album": {
            "album_type": "ALBUM",
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/1lZvg4fNAqHoj6I9N8naBM"
                    },
                    "href": "https://api.spotify.com/v1/artists/1lZvg4fNAqHoj6I9N8naBM",
                    "id": "1lZvg4fNAqHoj6I9N8naBM",
                    "name": "The Presidents Of The United States Of America",
                    "type": "artist",
                    "uri": "spotify:artist:1lZvg4fNAqHoj6I9N8naBM"
                }
            ],
            "available_markets": [],
            "external_urls": {
                "spotify": "https://open.spotify.com/album/3ItI6JFnsUIt5PajojH8kJ"
            },
            "href": "https://api.spotify.com/v1/albums/3ItI6JFnsUIt5PajojH8kJ",
            "id": "3ItI6JFnsUIt5PajojH8kJ",
            "images": [
                {
                    "height": 640,
                    "url": "https://i.scdn.co/image/ab67616d0000b273f9d98492936091b07a05f670",
                    "width": 640
                },
                {
                    "height": 300,
                    "url": "https://i.scdn.co/image/ab67616d00001e02f9d98492936091b07a05f670",
                    "width": 300
                },
                {
                    "height": 64,
                    "url": "https://i.scdn.co/image/ab67616d00004851f9d98492936091b07a05f670",
                    "width": 64
                }
            ],
            "name": "The Presidents of The United States of America: Ten Year Super Bonus Special Anniversary Edition",
            "release_date": "1995",
            "release_date_precision": "year",
            "total_tracks": 26,
            "type": "album",
            "uri": "spotify:album:3ItI6JFnsUIt5PajojH8kJ"
        },
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/1lZvg4fNAqHoj6I9N8naBM"
                },
                "href": "https://api.spotify.com/v1/artists/1lZvg4fNAqHoj6I9N8naBM",
                "id": "1lZvg4fNAqHoj6I9N8naBM",
                "name": "The Presidents Of The United States Of America",
                "type": "artist",
                "uri": "spotify:artist:1lZvg4fNAqHoj6I9N8naBM"
            }
        ],
        "available_markets": [],
        "disc_number": 1,
        "duration_ms": 171693,
        "explicit": false,
        "external_ids": {
            "isrc": "US35G0400026"
        },
        "external_urls": {
            "spotify": "https://open.spotify.com/track/5uxb9mE0Jd4oEEECxmNxbP"
        },
        "href": "https://api.spotify.com/v1/tracks/5uxb9mE0Jd4oEEECxmNxbP",
        "id": "5uxb9mE0Jd4oEEECxmNxbP",
        "is_local": false,
        "name": "Peaches",
        "popularity": 0,
        "preview_url": null,
        "track_number": 6,
        "type": "track",
        "uri": "spotify:track:5uxb9mE0Jd4oEEECxmNxbP"
    },
    {
        "album": {
            "album_type": "ALBUM",
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/3LTXHU3DhiYzGIgF2PP8Q8"
                    },
                    "href": "https://api.spotify.com/v1/artists/3LTXHU3DhiYzGIgF2PP8Q8",
                    "id": "3LTXHU3DhiYzGIgF2PP8Q8",
                    "name": "The Raveonettes",
                    "type": "artist",
                    "uri": "spotify:artist:3LTXHU3DhiYzGIgF2PP8Q8"
                }
            ],
            "available_markets": [
                "AR",
                "AU",
                "AT",
                "BE",
                "BO",
                "BR",
                "BG",
                "CA",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DK",
                "DO",
                "DE",
                "EC",
                "EE",
                "SV",
                "FI",
                "FR",
                "GR",
                "GT",
                "HN",
                "HK",
                "HU",
                "IS",
                "IE",
                "IT",
                "LV",
                "LT",
                "LU",
                "MY",
                "MT",
                "MX",
                "NL",
                "NZ",
                "NI",
                "NO",
                "PA",
                "PY",
                "PE",
                "PH",
                "PL",
                "PT",
                "SG",
                "SK",
                "ES",
                "SE",
                "CH",
                "TW",
                "TR",
                "UY",
                "US",
                "GB",
                "AD",
                "LI",
                "MC",
                "ID",
                "JP",
                "TH",
                "VN",
                "RO",
                "IL",
                "ZA",
                "SA",
                "AE",
                "BH",
                "QA",
                "OM",
                "KW",
                "EG",
                "MA",
                "DZ",
                "TN",
                "LB",
                "JO",
                "PS",
                "IN",
                "BY",
                "KZ",
                "MD",
                "UA",
                "AL",
                "BA",
                "HR",
                "ME",
                "MK",
                "RS",
                "SI",
                "KR",
                "BD",
                "PK",
                "LK",
                "GH",
                "KE",
                "NG",
                "TZ",
                "UG",
                "AG",
                "AM",
                "BS",
                "BB",
                "BZ",
                "BT",
                "BW",
                "BF",
                "CV",
                "CW",
                "DM",
                "FJ",
                "GM",
                "GE",
                "GD",
                "GW",
                "GY",
                "HT",
                "JM",
                "KI",
                "LS",
                "LR",
                "MW",
                "MV",
                "ML",
                "MH",
                "FM",
                "NA",
                "NR",
                "NE",
                "PW",
                "PG",
                "WS",
                "SM",
                "ST",
                "SN",
                "SC",
                "SL",
                "SB",
                "KN",
                "LC",
                "VC",
                "SR",
                "TL",
                "TO",
                "TT",
                "TV",
                "VU",
                "AZ",
                "BN",
                "BI",
                "KH",
                "CM",
                "TD",
                "KM",
                "GQ",
                "SZ",
                "GA",
                "GN",
                "KG",
                "LA",
                "MO",
                "MR",
                "MN",
                "NP",
                "RW",
                "TG",
                "UZ",
                "ZW",
                "BJ",
                "MG",
                "MU",
                "MZ",
                "AO",
                "CI",
                "DJ",
                "ZM",
                "CD",
                "CG",
                "IQ",
                "LY",
                "TJ",
                "VE",
                "ET",
                "XK"
            ],
            "external_urls": {
                "spotify": "https://open.spotify.com/album/1BctsbsuOFWweAMqlpbwNv"
            },
            "href": "https://api.spotify.com/v1/albums/1BctsbsuOFWweAMqlpbwNv",
            "id": "1BctsbsuOFWweAMqlpbwNv",
            "images": [
                {
                    "height": 640,
                    "url": "https://i.scdn.co/image/ab67616d0000b27303841522960c593658d650fb",
                    "width": 640
                },
                {
                    "height": 300,
                    "url": "https://i.scdn.co/image/ab67616d00001e0203841522960c593658d650fb",
                    "width": 300
                },
                {
                    "height": 64,
                    "url": "https://i.scdn.co/image/ab67616d0000485103841522960c593658d650fb",
                    "width": 64
                }
            ],
            "name": "Pe'ahi",
            "release_date": "2014-07-22",
            "release_date_precision": "day",
            "total_tracks": 10,
            "type": "album",
            "uri": "spotify:album:1BctsbsuOFWweAMqlpbwNv"
        },
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/3LTXHU3DhiYzGIgF2PP8Q8"
                },
                "href": "https://api.spotify.com/v1/artists/3LTXHU3DhiYzGIgF2PP8Q8",
                "id": "3LTXHU3DhiYzGIgF2PP8Q8",
                "name": "The Raveonettes",
                "type": "artist",
                "uri": "spotify:artist:3LTXHU3DhiYzGIgF2PP8Q8"
            }
        ],
        "available_markets": [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK"
        ],
        "disc_number": 1,
        "duration_ms": 174693,
        "explicit": true,
        "external_ids": {
            "isrc": "QMJW51400032"
        },
        "external_urls": {
            "spotify": "https://open.spotify.com/track/1NiqejimykCudqSql1KQUi"
        },
        "href": "https://api.spotify.com/v1/tracks/1NiqejimykCudqSql1KQUi",
        "id": "1NiqejimykCudqSql1KQUi",
        "is_local": false,
        "name": "Endless Sleeper",
        "popularity": 25,
        "preview_url": "https://p.scdn.co/mp3-preview/c26eb335b69fb82bb2ca79c08b978148aa0f9738?cid=9d8e34b48e744e6e868879cd20d1a9a3",
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:1NiqejimykCudqSql1KQUi"
    },
    {
        "album": {
            "album_type": "ALBUM",
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/4uN3DsfENc7dp0OLO0FEIb"
                    },
                    "href": "https://api.spotify.com/v1/artists/4uN3DsfENc7dp0OLO0FEIb",
                    "id": "4uN3DsfENc7dp0OLO0FEIb",
                    "name": "Sugar Ray",
                    "type": "artist",
                    "uri": "spotify:artist:4uN3DsfENc7dp0OLO0FEIb"
                }
            ],
            "available_markets": [
                "AD",
                "AG",
                "AL",
                "AM",
                "AR",
                "AT",
                "AZ",
                "BA",
                "BB",
                "BE",
                "BF",
                "BG",
                "BO",
                "BR",
                "BS",
                "BW",
                "BY",
                "BZ",
                "CA",
                "CH",
                "CL",
                "CO",
                "CR",
                "CV",
                "CW",
                "CY",
                "CZ",
                "DE",
                "DK",
                "DM",
                "DO",
                "EC",
                "EE",
                "ES",
                "FI",
                "FJ",
                "FM",
                "FR",
                "GB",
                "GD",
                "GH",
                "GM",
                "GR",
                "GT",
                "GW",
                "GY",
                "HN",
                "HR",
                "HU",
                "IE",
                "IL",
                "IN",
                "IS",
                "IT",
                "JP",
                "KE",
                "KG",
                "KN",
                "KZ",
                "LI",
                "LT",
                "LU",
                "LV",
                "MC",
                "MD",
                "ME",
                "MK",
                "MN",
                "MT",
                "MU",
                "MX",
                "MZ",
                "NA",
                "NE",
                "NG",
                "NI",
                "NL",
                "NO",
                "NP",
                "PA",
                "PE",
                "PG",
                "PL",
                "PT",
                "PY",
                "RO",
                "RS",
                "SE",
                "SI",
                "SK",
                "SM",
                "SR",
                "SV",
                "SZ",
                "TD",
                "TJ",
                "TR",
                "TT",
                "UA",
                "UG",
                "US",
                "UY",
                "UZ",
                "VE",
                "XK",
                "ZA",
                "ZW"
            ],
            "external_urls": {
                "spotify": "https://open.spotify.com/album/43NNW7iDuAE8pIouzvwWWi"
            },
            "href": "https://api.spotify.com/v1/albums/43NNW7iDuAE8pIouzvwWWi",
            "id": "43NNW7iDuAE8pIouzvwWWi",
            "images": [
                {
                    "height": 640,
                    "url": "https://i.scdn.co/image/ab67616d0000b273d4d4c752eccb62aa42f6487d",
                    "width": 640
                },
                {
                    "height": 300,
                    "url": "https://i.scdn.co/image/ab67616d00001e02d4d4c752eccb62aa42f6487d",
                    "width": 300
                },
                {
                    "height": 64,
                    "url": "https://i.scdn.co/image/ab67616d00004851d4d4c752eccb62aa42f6487d",
                    "width": 64
                }
            ],
            "name": "14:59",
            "release_date": "1998-12-23",
            "release_date_precision": "day",
            "total_tracks": 13,
            "type": "album",
            "uri": "spotify:album:43NNW7iDuAE8pIouzvwWWi"
        },
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/4uN3DsfENc7dp0OLO0FEIb"
                },
                "href": "https://api.spotify.com/v1/artists/4uN3DsfENc7dp0OLO0FEIb",
                "id": "4uN3DsfENc7dp0OLO0FEIb",
                "name": "Sugar Ray",
                "type": "artist",
                "uri": "spotify:artist:4uN3DsfENc7dp0OLO0FEIb"
            }
        ],
        "available_markets": [
            "AD",
            "AG",
            "AL",
            "AM",
            "AR",
            "AT",
            "AZ",
            "BA",
            "BB",
            "BE",
            "BF",
            "BG",
            "BO",
            "BR",
            "BS",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DM",
            "DO",
            "EC",
            "EE",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GB",
            "GD",
            "GH",
            "GM",
            "GR",
            "GT",
            "GW",
            "GY",
            "HN",
            "HR",
            "HU",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JP",
            "KE",
            "KG",
            "KN",
            "KZ",
            "LI",
            "LT",
            "LU",
            "LV",
            "MC",
            "MD",
            "ME",
            "MK",
            "MN",
            "MT",
            "MU",
            "MX",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "PA",
            "PE",
            "PG",
            "PL",
            "PT",
            "PY",
            "RO",
            "RS",
            "SE",
            "SI",
            "SK",
            "SM",
            "SR",
            "SV",
            "SZ",
            "TD",
            "TJ",
            "TR",
            "TT",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VE",
            "XK",
            "ZA",
            "ZW"
        ],
        "disc_number": 1,
        "duration_ms": 255160,
        "explicit": false,
        "external_ids": {
            "isrc": "USAT20902981"
        },
        "external_urls": {
            "spotify": "https://open.spotify.com/track/4T7fVN4ZOFE3JoGyaxZL6O"
        },
        "href": "https://api.spotify.com/v1/tracks/4T7fVN4ZOFE3JoGyaxZL6O",
        "id": "4T7fVN4ZOFE3JoGyaxZL6O",
        "is_local": false,
        "name": "Falls Apart",
        "popularity": 42,
        "preview_url": "https://p.scdn.co/mp3-preview/444c227c909bb4c1438bc899173d4db33c02c15a?cid=9d8e34b48e744e6e868879cd20d1a9a3",
        "track_number": 3,
        "type": "track",
        "uri": "spotify:track:4T7fVN4ZOFE3JoGyaxZL6O"
    },
    {
        "album": {
            "album_type": "ALBUM",
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/6qyi8X6MdP1lu6B1K6yh3h"
                    },
                    "href": "https://api.spotify.com/v1/artists/6qyi8X6MdP1lu6B1K6yh3h",
                    "id": "6qyi8X6MdP1lu6B1K6yh3h",
                    "name": "Silversun Pickups",
                    "type": "artist",
                    "uri": "spotify:artist:6qyi8X6MdP1lu6B1K6yh3h"
                }
            ],
            "available_markets": [],
            "external_urls": {
                "spotify": "https://open.spotify.com/album/2vqmxUBdGbY2OY3aSZ05Zx"
            },
            "href": "https://api.spotify.com/v1/albums/2vqmxUBdGbY2OY3aSZ05Zx",
            "id": "2vqmxUBdGbY2OY3aSZ05Zx",
            "images": [
                {
                    "height": 640,
                    "url": "https://i.scdn.co/image/ab67616d0000b2734d267bbe9dbc8c5ea38c80db",
                    "width": 640
                },
                {
                    "height": 300,
                    "url": "https://i.scdn.co/image/ab67616d00001e024d267bbe9dbc8c5ea38c80db",
                    "width": 300
                },
                {
                    "height": 64,
                    "url": "https://i.scdn.co/image/ab67616d000048514d267bbe9dbc8c5ea38c80db",
                    "width": 64
                }
            ],
            "name": "Neck Of The Woods",
            "release_date": "2012-05-08",
            "release_date_precision": "day",
            "total_tracks": 11,
            "type": "album",
            "uri": "spotify:album:2vqmxUBdGbY2OY3aSZ05Zx"
        },
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/6qyi8X6MdP1lu6B1K6yh3h"
                },
                "href": "https://api.spotify.com/v1/artists/6qyi8X6MdP1lu6B1K6yh3h",
                "id": "6qyi8X6MdP1lu6B1K6yh3h",
                "name": "Silversun Pickups",
                "type": "artist",
                "uri": "spotify:artist:6qyi8X6MdP1lu6B1K6yh3h"
            }
        ],
        "available_markets": [],
        "disc_number": 1,
        "duration_ms": 279600,
        "explicit": false,
        "external_ids": {
            "isrc": "US3R21208308"
        },
        "external_urls": {
            "spotify": "https://open.spotify.com/track/5EZGI150qdlQg99RUnkItZ"
        },
        "href": "https://api.spotify.com/v1/tracks/5EZGI150qdlQg99RUnkItZ",
        "id": "5EZGI150qdlQg99RUnkItZ",
        "is_local": false,
        "name": "The Pit",
        "popularity": 0,
        "preview_url": null,
        "track_number": 8,
        "type": "track",
        "uri": "spotify:track:5EZGI150qdlQg99RUnkItZ"
    },
    {
        "album": {
            "album_type": "SINGLE",
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/2fhngmJMaaKcdhXHCa4cPK"
                    },
                    "href": "https://api.spotify.com/v1/artists/2fhngmJMaaKcdhXHCa4cPK",
                    "id": "2fhngmJMaaKcdhXHCa4cPK",
                    "name": "The Dead Milkmen",
                    "type": "artist",
                    "uri": "spotify:artist:2fhngmJMaaKcdhXHCa4cPK"
                }
            ],
            "available_markets": [],
            "external_urls": {
                "spotify": "https://open.spotify.com/album/5v1j6dfClseuaIPme0OenM"
            },
            "href": "https://api.spotify.com/v1/albums/5v1j6dfClseuaIPme0OenM",
            "id": "5v1j6dfClseuaIPme0OenM",
            "images": [
                {
                    "height": 640,
                    "url": "https://i.scdn.co/image/ab67616d0000b273022955ffceb77d459b94ff73",
                    "width": 640
                },
                {
                    "height": 300,
                    "url": "https://i.scdn.co/image/ab67616d00001e02022955ffceb77d459b94ff73",
                    "width": 300
                },
                {
                    "height": 64,
                    "url": "https://i.scdn.co/image/ab67616d00004851022955ffceb77d459b94ff73",
                    "width": 64
                }
            ],
            "name": "Big Words Make The Baby Jesus Cry",
            "release_date": "2012-12-21",
            "release_date_precision": "day",
            "total_tracks": 3,
            "type": "album",
            "uri": "spotify:album:5v1j6dfClseuaIPme0OenM"
        },
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/2fhngmJMaaKcdhXHCa4cPK"
                },
                "href": "https://api.spotify.com/v1/artists/2fhngmJMaaKcdhXHCa4cPK",
                "id": "2fhngmJMaaKcdhXHCa4cPK",
                "name": "The Dead Milkmen",
                "type": "artist",
                "uri": "spotify:artist:2fhngmJMaaKcdhXHCa4cPK"
            }
        ],
        "available_markets": [],
        "disc_number": 1,
        "duration_ms": 185077,
        "explicit": false,
        "external_ids": {
            "isrc": "USGCV1287605"
        },
        "external_urls": {
            "spotify": "https://open.spotify.com/track/1B0l7bAVCezozz0gVa1dZA"
        },
        "href": "https://api.spotify.com/v1/tracks/1B0l7bAVCezozz0gVa1dZA",
        "id": "1B0l7bAVCezozz0gVa1dZA",
        "is_local": false,
        "name": "Big Words Make The Baby Jesus Cry",
        "popularity": 0,
        "preview_url": null,
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:1B0l7bAVCezozz0gVa1dZA"
    },
    {
        "album": {
            "album_type": "ALBUM",
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/0fWvSXbvztkeHEnEuYvU2A"
                    },
                    "href": "https://api.spotify.com/v1/artists/0fWvSXbvztkeHEnEuYvU2A",
                    "id": "0fWvSXbvztkeHEnEuYvU2A",
                    "name": "Bob Mould",
                    "type": "artist",
                    "uri": "spotify:artist:0fWvSXbvztkeHEnEuYvU2A"
                }
            ],
            "available_markets": [
                "AR",
                "AU",
                "AT",
                "BE",
                "BO",
                "BR",
                "BG",
                "CA",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DK",
                "DO",
                "DE",
                "EC",
                "EE",
                "SV",
                "FI",
                "FR",
                "GR",
                "GT",
                "HN",
                "HK",
                "HU",
                "IS",
                "IE",
                "IT",
                "LV",
                "LT",
                "LU",
                "MY",
                "MT",
                "MX",
                "NL",
                "NZ",
                "NI",
                "NO",
                "PA",
                "PY",
                "PE",
                "PH",
                "PL",
                "PT",
                "SG",
                "SK",
                "ES",
                "SE",
                "CH",
                "TW",
                "TR",
                "UY",
                "US",
                "GB",
                "AD",
                "LI",
                "MC",
                "ID",
                "TH",
                "VN",
                "RO",
                "IL",
                "ZA",
                "SA",
                "AE",
                "BH",
                "QA",
                "OM",
                "KW",
                "EG",
                "MA",
                "DZ",
                "TN",
                "LB",
                "JO",
                "PS",
                "IN",
                "BY",
                "KZ",
                "MD",
                "UA",
                "AL",
                "BA",
                "HR",
                "ME",
                "MK",
                "RS",
                "SI",
                "KR",
                "BD",
                "PK",
                "LK",
                "GH",
                "KE",
                "NG",
                "TZ",
                "UG",
                "AG",
                "AM",
                "BS",
                "BB",
                "BZ",
                "BT",
                "BW",
                "BF",
                "CV",
                "CW",
                "DM",
                "FJ",
                "GM",
                "GE",
                "GD",
                "GW",
                "GY",
                "HT",
                "JM",
                "KI",
                "LS",
                "LR",
                "MW",
                "MV",
                "ML",
                "MH",
                "FM",
                "NA",
                "NR",
                "NE",
                "PW",
                "PG",
                "WS",
                "SM",
                "ST",
                "SN",
                "SC",
                "SL",
                "SB",
                "KN",
                "LC",
                "VC",
                "SR",
                "TL",
                "TO",
                "TT",
                "TV",
                "VU",
                "AZ",
                "BN",
                "BI",
                "KH",
                "CM",
                "TD",
                "KM",
                "GQ",
                "SZ",
                "GA",
                "GN",
                "KG",
                "LA",
                "MO",
                "MR",
                "MN",
                "NP",
                "RW",
                "TG",
                "UZ",
                "ZW",
                "BJ",
                "MG",
                "MU",
                "MZ",
                "AO",
                "CI",
                "DJ",
                "ZM",
                "CD",
                "CG",
                "IQ",
                "LY",
                "TJ",
                "VE",
                "ET",
                "XK"
            ],
            "external_urls": {
                "spotify": "https://open.spotify.com/album/3VhSB8ozURez6qOSptLb15"
            },
            "href": "https://api.spotify.com/v1/albums/3VhSB8ozURez6qOSptLb15",
            "id": "3VhSB8ozURez6qOSptLb15",
            "images": [
                {
                    "height": 640,
                    "url": "https://i.scdn.co/image/ab67616d0000b273c09d0759175534092784264d",
                    "width": 640
                },
                {
                    "height": 300,
                    "url": "https://i.scdn.co/image/ab67616d00001e02c09d0759175534092784264d",
                    "width": 300
                },
                {
                    "height": 64,
                    "url": "https://i.scdn.co/image/ab67616d00004851c09d0759175534092784264d",
                    "width": 64
                }
            ],
            "name": "Workbook",
            "release_date": "1989",
            "release_date_precision": "year",
            "total_tracks": 17,
            "type": "album",
            "uri": "spotify:album:3VhSB8ozURez6qOSptLb15"
        },
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/0fWvSXbvztkeHEnEuYvU2A"
                },
                "href": "https://api.spotify.com/v1/artists/0fWvSXbvztkeHEnEuYvU2A",
                "id": "0fWvSXbvztkeHEnEuYvU2A",
                "name": "Bob Mould",
                "type": "artist",
                "uri": "spotify:artist:0fWvSXbvztkeHEnEuYvU2A"
            }
        ],
        "available_markets": [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK"
        ],
        "disc_number": 1,
        "duration_ms": 212066,
        "explicit": false,
        "external_ids": {
            "isrc": "USVI29401087"
        },
        "external_urls": {
            "spotify": "https://open.spotify.com/track/7LdKMBKthcdBnAqlAIGqCB"
        },
        "href": "https://api.spotify.com/v1/tracks/7LdKMBKthcdBnAqlAIGqCB",
        "id": "7LdKMBKthcdBnAqlAIGqCB",
        "is_local": false,
        "name": "See A Little Light",
        "popularity": 38,
        "preview_url": null,
        "track_number": 4,
        "type": "track",
        "uri": "spotify:track:7LdKMBKthcdBnAqlAIGqCB"
    },
    {
        "album": {
            "album_type": "COMPILATION",
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of"
                    },
                    "href": "https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of",
                    "id": "0LyfQWJT6nXafLPZqxe9Of",
                    "name": "Various Artists",
                    "type": "artist",
                    "uri": "spotify:artist:0LyfQWJT6nXafLPZqxe9Of"
                }
            ],
            "available_markets": [
                "AR",
                "AT",
                "BE",
                "BO",
                "BR",
                "BG",
                "CA",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DK",
                "DO",
                "DE",
                "EC",
                "EE",
                "SV",
                "FI",
                "FR",
                "GR",
                "GT",
                "HN",
                "HK",
                "HU",
                "IS",
                "IE",
                "IT",
                "LV",
                "LT",
                "LU",
                "MY",
                "MT",
                "NL",
                "NZ",
                "NI",
                "NO",
                "PA",
                "PY",
                "PE",
                "PH",
                "PL",
                "PT",
                "SG",
                "SK",
                "ES",
                "SE",
                "CH",
                "TW",
                "TR",
                "UY",
                "US",
                "GB",
                "AD",
                "LI",
                "MC",
                "ID",
                "JP",
                "TH",
                "VN",
                "RO",
                "IL",
                "ZA",
                "SA",
                "AE",
                "BH",
                "QA",
                "OM",
                "KW",
                "EG",
                "MA",
                "DZ",
                "TN",
                "LB",
                "JO",
                "PS",
                "IN",
                "BY",
                "KZ",
                "MD",
                "UA",
                "AL",
                "BA",
                "HR",
                "ME",
                "MK",
                "RS",
                "SI",
                "KR",
                "BD",
                "PK",
                "LK",
                "GH",
                "KE",
                "NG",
                "TZ",
                "UG",
                "AG",
                "AM",
                "BS",
                "BB",
                "BZ",
                "BW",
                "BF",
                "CV",
                "CW",
                "DM",
                "FJ",
                "GM",
                "GD",
                "GW",
                "HT",
                "JM",
                "LS",
                "LR",
                "MW",
                "ML",
                "FM",
                "NA",
                "NE",
                "PG",
                "SM",
                "ST",
                "SN",
                "SC",
                "SL",
                "KN",
                "LC",
                "VC",
                "TL",
                "TT",
                "AZ",
                "BN",
                "BI",
                "KH",
                "CM",
                "TD",
                "KM",
                "GQ",
                "SZ",
                "GA",
                "GN",
                "KG",
                "LA",
                "MO",
                "MR",
                "MN",
                "NP",
                "RW",
                "TG",
                "UZ",
                "ZW",
                "BJ",
                "MG",
                "MU",
                "MZ",
                "AO",
                "CI",
                "DJ",
                "ZM",
                "CD",
                "CG",
                "IQ",
                "LY",
                "TJ",
                "VE",
                "ET",
                "XK"
            ],
            "external_urls": {
                "spotify": "https://open.spotify.com/album/76DxuvfdC3lmCDLFf6rSWw"
            },
            "href": "https://api.spotify.com/v1/albums/76DxuvfdC3lmCDLFf6rSWw",
            "id": "76DxuvfdC3lmCDLFf6rSWw",
            "images": [
                {
                    "height": 640,
                    "url": "https://i.scdn.co/image/ab67616d0000b273056b40e9277155c3652a81e2",
                    "width": 640
                },
                {
                    "height": 300,
                    "url": "https://i.scdn.co/image/ab67616d00001e02056b40e9277155c3652a81e2",
                    "width": 300
                },
                {
                    "height": 64,
                    "url": "https://i.scdn.co/image/ab67616d00004851056b40e9277155c3652a81e2",
                    "width": 64
                }
            ],
            "name": "Ronnie James Dio - This Is Your Life",
            "release_date": "2014-03-31",
            "release_date_precision": "day",
            "total_tracks": 15,
            "type": "album",
            "uri": "spotify:album:76DxuvfdC3lmCDLFf6rSWw"
        },
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/1XpDYCrUJnvCo9Ez6yeMWh"
                },
                "href": "https://api.spotify.com/v1/artists/1XpDYCrUJnvCo9Ez6yeMWh",
                "id": "1XpDYCrUJnvCo9Ez6yeMWh",
                "name": "Tenacious D",
                "type": "artist",
                "uri": "spotify:artist:1XpDYCrUJnvCo9Ez6yeMWh"
            }
        ],
        "available_markets": [
            "AR",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GD",
            "GW",
            "HT",
            "JM",
            "LS",
            "LR",
            "MW",
            "ML",
            "FM",
            "NA",
            "NE",
            "PG",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "KN",
            "LC",
            "VC",
            "TL",
            "TT",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK"
        ],
        "disc_number": 1,
        "duration_ms": 223773,
        "explicit": false,
        "external_ids": {
            "isrc": "USRH11400077"
        },
        "external_urls": {
            "spotify": "https://open.spotify.com/track/7cuIQgdm380dPia0PyQAc8"
        },
        "href": "https://api.spotify.com/v1/tracks/7cuIQgdm380dPia0PyQAc8",
        "id": "7cuIQgdm380dPia0PyQAc8",
        "is_local": false,
        "name": "The Last In Line",
        "popularity": 45,
        "preview_url": "https://p.scdn.co/mp3-preview/44326ce346bfa75aadf76f4e42a9ac88941fd85b?cid=9d8e34b48e744e6e868879cd20d1a9a3",
        "track_number": 2,
        "type": "track",
        "uri": "spotify:track:7cuIQgdm380dPia0PyQAc8"
    },
    {
        "album": {
            "album_type": "ALBUM",
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/6zB02lwP6L6ZH32nggQiJT"
                    },
                    "href": "https://api.spotify.com/v1/artists/6zB02lwP6L6ZH32nggQiJT",
                    "id": "6zB02lwP6L6ZH32nggQiJT",
                    "name": "They Might Be Giants",
                    "type": "artist",
                    "uri": "spotify:artist:6zB02lwP6L6ZH32nggQiJT"
                }
            ],
            "available_markets": [],
            "external_urls": {
                "spotify": "https://open.spotify.com/album/3ORYx3NI69H9WGezyKAJhM"
            },
            "href": "https://api.spotify.com/v1/albums/3ORYx3NI69H9WGezyKAJhM",
            "id": "3ORYx3NI69H9WGezyKAJhM",
            "images": [
                {
                    "height": 640,
                    "url": "https://i.scdn.co/image/ab67616d0000b2733efc9f2417cce2be73e7f265",
                    "width": 640
                },
                {
                    "height": 300,
                    "url": "https://i.scdn.co/image/ab67616d00001e023efc9f2417cce2be73e7f265",
                    "width": 300
                },
                {
                    "height": 64,
                    "url": "https://i.scdn.co/image/ab67616d000048513efc9f2417cce2be73e7f265",
                    "width": 64
                }
            ],
            "name": "Nanobots",
            "release_date": "2013-03-05",
            "release_date_precision": "day",
            "total_tracks": 25,
            "type": "album",
            "uri": "spotify:album:3ORYx3NI69H9WGezyKAJhM"
        },
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/6zB02lwP6L6ZH32nggQiJT"
                },
                "href": "https://api.spotify.com/v1/artists/6zB02lwP6L6ZH32nggQiJT",
                "id": "6zB02lwP6L6ZH32nggQiJT",
                "name": "They Might Be Giants",
                "type": "artist",
                "uri": "spotify:artist:6zB02lwP6L6ZH32nggQiJT"
            }
        ],
        "available_markets": [],
        "disc_number": 1,
        "duration_ms": 161706,
        "explicit": false,
        "external_ids": {
            "isrc": "USME31202303"
        },
        "external_urls": {
            "spotify": "https://open.spotify.com/track/1WqMWVafmQbUPFOQfuszFC"
        },
        "href": "https://api.spotify.com/v1/tracks/1WqMWVafmQbUPFOQfuszFC",
        "id": "1WqMWVafmQbUPFOQfuszFC",
        "is_local": false,
        "name": "You're On Fire",
        "popularity": 0,
        "preview_url": null,
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:1WqMWVafmQbUPFOQfuszFC"
    },
    {
        "album": {
            "album_type": "ALBUM",
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/3XR64HmFo4OvexUUNW7TP0"
                    },
                    "href": "https://api.spotify.com/v1/artists/3XR64HmFo4OvexUUNW7TP0",
                    "id": "3XR64HmFo4OvexUUNW7TP0",
                    "name": "Mother Love Bone",
                    "type": "artist",
                    "uri": "spotify:artist:3XR64HmFo4OvexUUNW7TP0"
                }
            ],
            "available_markets": [
                "AR",
                "AU",
                "AT",
                "BE",
                "BO",
                "BR",
                "BG",
                "CA",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DK",
                "DO",
                "DE",
                "EC",
                "EE",
                "SV",
                "FI",
                "FR",
                "GR",
                "GT",
                "HN",
                "HK",
                "HU",
                "IS",
                "IE",
                "IT",
                "LV",
                "LT",
                "LU",
                "MY",
                "MT",
                "MX",
                "NL",
                "NZ",
                "NI",
                "NO",
                "PA",
                "PY",
                "PE",
                "PH",
                "PL",
                "PT",
                "SG",
                "SK",
                "ES",
                "SE",
                "CH",
                "TW",
                "TR",
                "UY",
                "US",
                "GB",
                "AD",
                "LI",
                "MC",
                "ID",
                "JP",
                "TH",
                "VN",
                "RO",
                "IL",
                "ZA",
                "SA",
                "AE",
                "BH",
                "QA",
                "OM",
                "KW",
                "EG",
                "MA",
                "DZ",
                "TN",
                "LB",
                "JO",
                "PS",
                "IN",
                "BY",
                "KZ",
                "MD",
                "UA",
                "AL",
                "BA",
                "HR",
                "ME",
                "MK",
                "RS",
                "SI",
                "KR",
                "BD",
                "PK",
                "LK",
                "GH",
                "KE",
                "NG",
                "TZ",
                "UG",
                "AG",
                "AM",
                "BS",
                "BB",
                "BZ",
                "BT",
                "BW",
                "BF",
                "CV",
                "CW",
                "DM",
                "FJ",
                "GM",
                "GE",
                "GD",
                "GW",
                "GY",
                "HT",
                "JM",
                "KI",
                "LS",
                "LR",
                "MW",
                "MV",
                "ML",
                "MH",
                "FM",
                "NA",
                "NR",
                "NE",
                "PW",
                "PG",
                "WS",
                "SM",
                "ST",
                "SN",
                "SC",
                "SL",
                "SB",
                "KN",
                "LC",
                "VC",
                "SR",
                "TL",
                "TO",
                "TT",
                "TV",
                "VU",
                "AZ",
                "BN",
                "BI",
                "KH",
                "CM",
                "TD",
                "KM",
                "GQ",
                "SZ",
                "GA",
                "GN",
                "KG",
                "LA",
                "MO",
                "MR",
                "MN",
                "NP",
                "RW",
                "TG",
                "UZ",
                "ZW",
                "BJ",
                "MG",
                "MU",
                "MZ",
                "AO",
                "CI",
                "DJ",
                "ZM",
                "CD",
                "CG",
                "IQ",
                "LY",
                "TJ",
                "VE",
                "ET",
                "XK"
            ],
            "external_urls": {
                "spotify": "https://open.spotify.com/album/5ohJawP6UajQ6ZIjWxnvM6"
            },
            "href": "https://api.spotify.com/v1/albums/5ohJawP6UajQ6ZIjWxnvM6",
            "id": "5ohJawP6UajQ6ZIjWxnvM6",
            "images": [
                {
                    "height": 640,
                    "url": "https://i.scdn.co/image/ab67616d0000b273336e295fdc07e9ee13778b4a",
                    "width": 640
                },
                {
                    "height": 300,
                    "url": "https://i.scdn.co/image/ab67616d00001e02336e295fdc07e9ee13778b4a",
                    "width": 300
                },
                {
                    "height": 64,
                    "url": "https://i.scdn.co/image/ab67616d00004851336e295fdc07e9ee13778b4a",
                    "width": 64
                }
            ],
            "name": "Mother Love Bone",
            "release_date": "1992-01-01",
            "release_date_precision": "day",
            "total_tracks": 17,
            "type": "album",
            "uri": "spotify:album:5ohJawP6UajQ6ZIjWxnvM6"
        },
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/3XR64HmFo4OvexUUNW7TP0"
                },
                "href": "https://api.spotify.com/v1/artists/3XR64HmFo4OvexUUNW7TP0",
                "id": "3XR64HmFo4OvexUUNW7TP0",
                "name": "Mother Love Bone",
                "type": "artist",
                "uri": "spotify:artist:3XR64HmFo4OvexUUNW7TP0"
            }
        ],
        "available_markets": [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK"
        ],
        "disc_number": 1,
        "duration_ms": 502040,
        "explicit": false,
        "external_ids": {
            "isrc": "USWWW0134840"
        },
        "external_urls": {
            "spotify": "https://open.spotify.com/track/7rBMZvgeWnOTHWUh3Pvw51"
        },
        "href": "https://api.spotify.com/v1/tracks/7rBMZvgeWnOTHWUh3Pvw51",
        "id": "7rBMZvgeWnOTHWUh3Pvw51",
        "is_local": false,
        "name": "Chloe Dancer/Crown Of Thorns",
        "popularity": 49,
        "preview_url": null,
        "track_number": 17,
        "type": "track",
        "uri": "spotify:track:7rBMZvgeWnOTHWUh3Pvw51"
    },
    {
        "album": {
            "album_type": "ALBUM",
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/0pbIqPTefLfuOcbM2ojXdl"
                    },
                    "href": "https://api.spotify.com/v1/artists/0pbIqPTefLfuOcbM2ojXdl",
                    "id": "0pbIqPTefLfuOcbM2ojXdl",
                    "name": "Polvo",
                    "type": "artist",
                    "uri": "spotify:artist:0pbIqPTefLfuOcbM2ojXdl"
                }
            ],
            "available_markets": [],
            "external_urls": {
                "spotify": "https://open.spotify.com/album/2obaFAoT1S2NnmTut0i04B"
            },
            "href": "https://api.spotify.com/v1/albums/2obaFAoT1S2NnmTut0i04B",
            "id": "2obaFAoT1S2NnmTut0i04B",
            "images": [
                {
                    "height": 640,
                    "url": "https://i.scdn.co/image/ab67616d0000b273546da5e5e983b856ad4c4e01",
                    "width": 640
                },
                {
                    "height": 300,
                    "url": "https://i.scdn.co/image/ab67616d00001e02546da5e5e983b856ad4c4e01",
                    "width": 300
                },
                {
                    "height": 64,
                    "url": "https://i.scdn.co/image/ab67616d00004851546da5e5e983b856ad4c4e01",
                    "width": 64
                }
            ],
            "name": "Siberia",
            "release_date": "2013-09-30",
            "release_date_precision": "day",
            "total_tracks": 8,
            "type": "album",
            "uri": "spotify:album:2obaFAoT1S2NnmTut0i04B"
        },
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/0pbIqPTefLfuOcbM2ojXdl"
                },
                "href": "https://api.spotify.com/v1/artists/0pbIqPTefLfuOcbM2ojXdl",
                "id": "0pbIqPTefLfuOcbM2ojXdl",
                "name": "Polvo",
                "type": "artist",
                "uri": "spotify:artist:0pbIqPTefLfuOcbM2ojXdl"
            }
        ],
        "available_markets": [],
        "disc_number": 1,
        "duration_ms": 386226,
        "explicit": false,
        "external_ids": {
            "isrc": "USMRG1341001"
        },
        "external_urls": {
            "spotify": "https://open.spotify.com/track/0CZ48zSBAXNplab4I4T4NN"
        },
        "href": "https://api.spotify.com/v1/tracks/0CZ48zSBAXNplab4I4T4NN",
        "id": "0CZ48zSBAXNplab4I4T4NN",
        "is_local": false,
        "name": "Total Immersion",
        "popularity": 0,
        "preview_url": null,
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:0CZ48zSBAXNplab4I4T4NN"
    },
    {
        "album": {
            "album_type": "ALBUM",
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/4xNadaO5ZZLVJdqDIVVIua"
                    },
                    "href": "https://api.spotify.com/v1/artists/4xNadaO5ZZLVJdqDIVVIua",
                    "id": "4xNadaO5ZZLVJdqDIVVIua",
                    "name": "Electric Six",
                    "type": "artist",
                    "uri": "spotify:artist:4xNadaO5ZZLVJdqDIVVIua"
                }
            ],
            "available_markets": [
                "AG",
                "AR",
                "BB",
                "BO",
                "BR",
                "BS",
                "BZ",
                "CA",
                "CL",
                "CO",
                "CR",
                "DM",
                "DO",
                "EC",
                "GD",
                "GT",
                "GY",
                "HN",
                "HT",
                "JM",
                "KN",
                "LC",
                "MX",
                "NI",
                "PA",
                "PE",
                "PY",
                "SR",
                "SV",
                "TT",
                "US",
                "UY",
                "VC",
                "VE"
            ],
            "external_urls": {
                "spotify": "https://open.spotify.com/album/21scKYhthIXT92OZrrqIB7"
            },
            "href": "https://api.spotify.com/v1/albums/21scKYhthIXT92OZrrqIB7",
            "id": "21scKYhthIXT92OZrrqIB7",
            "images": [
                {
                    "height": 640,
                    "url": "https://i.scdn.co/image/ab67616d0000b273dd531bcf75c511285adfbbc1",
                    "width": 640
                },
                {
                    "height": 300,
                    "url": "https://i.scdn.co/image/ab67616d00001e02dd531bcf75c511285adfbbc1",
                    "width": 300
                },
                {
                    "height": 64,
                    "url": "https://i.scdn.co/image/ab67616d00004851dd531bcf75c511285adfbbc1",
                    "width": 64
                }
            ],
            "name": "Human Zoo",
            "release_date": "2014-10-14",
            "release_date_precision": "day",
            "total_tracks": 12,
            "type": "album",
            "uri": "spotify:album:21scKYhthIXT92OZrrqIB7"
        },
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/4xNadaO5ZZLVJdqDIVVIua"
                },
                "href": "https://api.spotify.com/v1/artists/4xNadaO5ZZLVJdqDIVVIua",
                "id": "4xNadaO5ZZLVJdqDIVVIua",
                "name": "Electric Six",
                "type": "artist",
                "uri": "spotify:artist:4xNadaO5ZZLVJdqDIVVIua"
            }
        ],
        "available_markets": [
            "AG",
            "AR",
            "BB",
            "BO",
            "BR",
            "BS",
            "BZ",
            "CA",
            "CL",
            "CO",
            "CR",
            "DM",
            "DO",
            "EC",
            "GD",
            "GT",
            "GY",
            "HN",
            "HT",
            "JM",
            "KN",
            "LC",
            "MX",
            "NI",
            "PA",
            "PE",
            "PY",
            "SR",
            "SV",
            "TT",
            "US",
            "UY",
            "VC",
            "VE"
        ],
        "disc_number": 1,
        "duration_ms": 190426,
        "explicit": false,
        "external_ids": {
            "isrc": "US57M1495501"
        },
        "external_urls": {
            "spotify": "https://open.spotify.com/track/4DfGcn3VVcdmmJl1PWNAkv"
        },
        "href": "https://api.spotify.com/v1/tracks/4DfGcn3VVcdmmJl1PWNAkv",
        "id": "4DfGcn3VVcdmmJl1PWNAkv",
        "is_local": false,
        "name": "Karate Lips",
        "popularity": 8,
        "preview_url": "https://p.scdn.co/mp3-preview/4ab85d9470056990ef5a2e63b6ecc023c991b523?cid=9d8e34b48e744e6e868879cd20d1a9a3",
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:4DfGcn3VVcdmmJl1PWNAkv"
    },
    {
        "album": {
            "album_type": "ALBUM",
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/3inCNiUr4R6XQ3W43s9Aqi"
                    },
                    "href": "https://api.spotify.com/v1/artists/3inCNiUr4R6XQ3W43s9Aqi",
                    "id": "3inCNiUr4R6XQ3W43s9Aqi",
                    "name": "Pavement",
                    "type": "artist",
                    "uri": "spotify:artist:3inCNiUr4R6XQ3W43s9Aqi"
                }
            ],
            "available_markets": [],
            "external_urls": {
                "spotify": "https://open.spotify.com/album/4YqxiKEVG0OuwX0g2XWW99"
            },
            "href": "https://api.spotify.com/v1/albums/4YqxiKEVG0OuwX0g2XWW99",
            "id": "4YqxiKEVG0OuwX0g2XWW99",
            "images": [
                {
                    "height": 640,
                    "url": "https://i.scdn.co/image/ab67616d0000b273e327c130da6fb5f82224a13a",
                    "width": 640
                },
                {
                    "height": 300,
                    "url": "https://i.scdn.co/image/ab67616d00001e02e327c130da6fb5f82224a13a",
                    "width": 300
                },
                {
                    "height": 64,
                    "url": "https://i.scdn.co/image/ab67616d00004851e327c130da6fb5f82224a13a",
                    "width": 64
                }
            ],
            "name": "Crooked Rain, Crooked Rain: LA's Desert Origins",
            "release_date": "1994",
            "release_date_precision": "year",
            "total_tracks": 49,
            "type": "album",
            "uri": "spotify:album:4YqxiKEVG0OuwX0g2XWW99"
        },
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/3inCNiUr4R6XQ3W43s9Aqi"
                },
                "href": "https://api.spotify.com/v1/artists/3inCNiUr4R6XQ3W43s9Aqi",
                "id": "3inCNiUr4R6XQ3W43s9Aqi",
                "name": "Pavement",
                "type": "artist",
                "uri": "spotify:artist:3inCNiUr4R6XQ3W43s9Aqi"
            }
        ],
        "available_markets": [],
        "disc_number": 1,
        "duration_ms": 159973,
        "explicit": false,
        "external_ids": {
            "isrc": "USMTD9407907"
        },
        "external_urls": {
            "spotify": "https://open.spotify.com/track/0IVT2zUgpMzyEx2TTM1HgB"
        },
        "href": "https://api.spotify.com/v1/tracks/0IVT2zUgpMzyEx2TTM1HgB",
        "id": "0IVT2zUgpMzyEx2TTM1HgB",
        "is_local": false,
        "name": "Gold Soundz",
        "popularity": 0,
        "preview_url": null,
        "track_number": 7,
        "type": "track",
        "uri": "spotify:track:0IVT2zUgpMzyEx2TTM1HgB"
    }
]`

export const testTracks: Track[] = JSON.parse(testTracksJson)